### PR TITLE
Fix conflict with the name "values" in the ConfigDict

### PR DESCRIPTION
**Pull request by JanrainMicah**

### CODE REVIEW

**Comment by JanrainMicah** [comment]
The py2to3 flag in setup.py is going to replace instance of itervalues() with values() for Python 3. The ConfigDict is overriding the values function with an attribute (used internally).

File "/home/micah/checkout/janrain-dataload/venv/lib64/python3.4/site-packages/janrain/capture/config.py", line 19, in get_settings_at_path
yaml_dict = read_config_file()
File "/home/micah/checkout/janrain-dataload/venv/lib64/python3.4/site-packages/janrain/capture/config.py", line 130, in read_config_file
for client in config['clients'].values():
TypeError: 'dict' object is not callable

**Comment by rdenmark** [comment]
LGTM

**Comment by Janrain-Colin** [comment]
:ship::it:

**Comment by ebeesonjanrain** [comment]
Added a fix for an issue that was causing bytestrings and unicode to get mixed together in generate_signature() in python3

**Comment by Janrain-Colin** [comment]
:accept:

**Comment by ebeesonjanrain** [comment]
nevermind, my fix is incomplete - it falls over when passing json to the api

**Comment by ebeesonjanrain** [comment]
ok, fix should work properly now

**Comment by JanrainMicah** [comment]
Looks good but I'm going to run this against some more tests.

**Comment by JanrainMicah** [comment]
Still running into errors in Python 3 with signed requests. I'm going to see if I can strip it down into a test case this evening.

**Comment by JanrainMicah** [comment]
@ebeesonjanrain I added one more fix (build status in the README) but all else looks good. Ran tests in Py2 and Py3 including my scripts which were previously failing in Py3.

**Comment by ebeesonjanrain** [comment]
great - I'll do the release

**Pull request merged**
